on:
  pull_request:
    types: [closed]

jobs:
  prune:
    runs-on: ubuntu-latest

    steps:
      - name: Deactivate GitHub environment
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: 'Pull Request #${{ github.event.number }} Preview'
          desc: Deployment was pruned
